### PR TITLE
Update min version for CMake to build project

### PR DESCRIPTION
**Pull request by ugGit**
If using CMake v3.17.0, the build fails during the compilation of header files requiring c++17. E.g.:
```
[ 77%] Built target ActsCore
Scanning dependencies of target traccc_cuda
[ 77%] Building CUDA object device/cuda/CMakeFiles/traccc_cuda.dir/src/seeding/doublet_counting.cu.o
In file included from /home/nwachuch/traccc/build/_deps/vecmem-src/core/include/vecmem/containers/data/jagged_vector_buffer.hpp:12,
                 from /home/nwachuch/traccc/core/include/traccc/edm/container.hpp:14,
                 from /home/nwachuch/traccc/core/include/traccc/seeding/detail/singlet.hpp:11,
                 from /home/nwachuch/traccc/device/cuda/include/traccc/cuda/seeding/detail/doublet_counter.hpp:11,
                 from /home/nwachuch/traccc/device/cuda/include/traccc/cuda/seeding/doublet_counting.hpp:10,
                 from /home/nwachuch/traccc/device/cuda/src/seeding/[doublet_counting.cu:8](http://doublet_counting.cu:8/):
/home/nwachuch/traccc/build/_deps/vecmem-src/core/include/vecmem/memory/memory_resource.hpp:14:2: error: #error "This header can only be used in C++17 mode. " "Ideally it should only be used by the \"host compiler\"."
   14 | #error \
      |  ^~~~~
```
Project is successfully build using at least CMake 3.18.0.

### CODE REVIEW

**Comment by beomki-yeo** [comment]
Apparently, the cmake [here](https://github.com/acts-project/machines/blob/master/ubuntu2004/Dockerfile) should be updated

**Comment by stephenswat** [comment]
No comments on the pull request, but welcome to traccc! It's great to see new contributors here. :smile:

**Comment by krasznaa** [comment]
You know what, no... Let's instead add/update

```cmake
cmake_minimum_required( VERSION 3.18 )
```

in:

https://github.com/acts-project/traccc/blob/main/cmake/traccc-compiler-options-cuda.cmake#L8

Since that file should be explicitly included everywhere that we build CUDA code at, that should be a more robust way of solving this issue. Also then I don't need to ask @stephenswat to update #153 with a CMake 3.18 requirement. :wink:

**Comment by ugGit** [comment]
@krasznaa I made the suggeste change to reduce the CMake min version requirement only for the CUDA related CMakeFile.

**Comment by beomki-yeo** [comment]
If ubuntucuda has it already then it should be OK.

File: cmake/traccc-compiler-options-cuda.cmake [hunk 1]
```diff
@@ -5,7 +5,7 @@
 # Mozilla Public License Version 2.0
 
 # FindCUDAToolkit needs at least CMake 3.17.
```
[the remark this answers is not in the document]
Comment (ugGit) [reply cmake/traccc-compiler-options-cuda.cmake]: Good catch. I just made the corresponding change and committed them.

**Review by beomki-yeo — APPROVED** [review]

**Review by krasznaa — APPROVED** [review]
Now with the text set up to be a bit more correct as well. :stuck_out_tongue:

**Comment by stephenswat** [comment]
Let's merge this. Thank you for your contribution, Uchendu!
